### ISSUE TITLE
Incorrect attempt in Gender Confusion with correct answer.

### ISSUE THREAD

**Issue by arjun921** [theSage21/openJudge#14]
Gender confusion question shows incorrect answer even when compared with the test cases provided in the admin user.

**Comment by theSage21** [comment]
For those wondering, http://iiitmk.ac.in/prg/1/ is the place the contest is being hosted.  
To debug the issue:
- download the input and output files to your local machine.
- Do something to the effect `python myfile < input_file > my_program_output_file`
- Then compare the output file from your program and the expected one.

**Note**: Right now only strict string comparison is done, so it's expected that `1.0` is not equal to `1`.

**Comment by theSage21** [comment]
I've refactored everything so this should have gone away. Please check and confirm.
