### ISSUE TITLE
new installation

### ISSUE THREAD

**Issue by Dedock** [theSage21/openJudge#16]
Hi, thanks for your judge. 
Ububntu 14
I have successfully installed it but it doesn't see static files( 
Could you help me?

Mac OS
when i tried run server.sh i got this output
./server.sh: line 5: nproc: command not found
usage: gunicorn [OPTIONS] [APP_MODULE]
gunicorn: error: argument -w/--workers: expected one argument

**Comment by theSage21** [comment]
From what I can see, NPROC is failing.
After -w/--workers in the `server.sh` file just add a 4/8 or whatever number of processors you have.

Also, I'm in the midst of rewriting this entire thing so that it becomes a painless install and run. You might need to wait a while though. :smile:

**Comment by Dedock** [comment]
thanks for your reply, i will be very grateful if you will do it as soon as possible, or tell me how to fix it right now.

**Comment by theSage21** [comment]
For OS X I've already mentioned that inserting a number after `-w` will get you out of trouble. On Ubuntu, the `setup.sh` does everything. You'll need to be more specific in that scene.

Most of the times it is a permissions issue if static files are not getting served.

**Comment by Dedock** [comment]
I add a number after -w, but it didn't solve my problem( I think the problem is somewhere in nginx config or in website/settings.py. May you check if there are some problems and give me sample nging config

**Comment by theSage21** [comment]
I had based my version on the [Gunicorn Docs](http://docs.gunicorn.org/en/stable/deploy.html). Perhaps they can help.  Thank you so much for using openJudge! I've redoubled my efforts to bring the new version to light as soon as possible. A few more days and it should be ready in my opinion.

**Comment by Dedock** [comment]
Thanks a lot for your help! If you do it, you will save my life)

**Comment by theSage21** [comment]
So I've pushed the new version. Make sure that you go through the README before trying it out. I'll keep this issue open so that if any errors arise we can solve them here.

**Comment by Dedock** [comment]
I read readme carefully, I have installed python 3.5+.  but how can I totally switch my machine to it?
now I have such output (((
sudo pip install openjudge
The directory '/home/oleg/.cache/pip/http' or its parent directory is not owned by the current user and the cache has been disabled. Please check the permissions and owner of that directory. If executing pip with sudo, you may want sudo's -H flag.
The directory '/home/oleg/.cache/pip' or its parent directory is not owned by the current user and caching wheels has been disabled. check the permissions and owner of that directory. If executing pip with sudo, you may want sudo's -H flag.
Collecting openjudge
/usr/local/lib/python2.7/dist-packages/pip/_vendor/requests/packages/urllib3/util/ssl_.py:318: SNIMissingWarning: An HTTPS request has been made, but the SNI (Subject Name Indication) extension to TLS is not available on this platform. This may cause the server to present an incorrect TLS certificate, which can cause validation failures. You can upgrade to a newer version of Python to solve this. For more information, see https://urllib3.readthedocs.io/en/latest/security.html#snimissingwarning.
  SNIMissingWarning
/usr/local/lib/python2.7/dist-packages/pip/_vendor/requests/packages/urllib3/util/ssl_.py:122: InsecurePlatformWarning: A true SSLContext object is not available. This prevents urllib3 from configuring SSL appropriately and may cause certain SSL connections to fail. You can upgrade to a newer version of Python to solve this. For more information, see https://urllib3.readthedocs.io/en/latest/security.html#insecureplatformwarning.
  InsecurePlatformWarning
  Downloading openjudge-2.0.4.tar.gz (43kB)
    100% |████████████████████████████████| 51kB 742kB/s 
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-build-Zs1DSn/openjudge/setup.py", line 7, in <module>
        raise Exception('You require Python3.5 or above to run OpenJudge')
    Exception: You require Python3.5 or above to run OpenJudge
    
    ----------------------------------------
Command "python setup.py egg_info" failed with error code 1 in /tmp/pip-build-Zs1DSn/openjudge/

**Comment by theSage21** [comment]
@Dedock are you running this on Ubuntu?
In case you are here's a set of commands that should get you going right away.

To install python3.5 on your machine (Even though you have installed this, I am putting it here for completeness sake).
```bash
sudo apt-get install python-virtualenv
sudo add-apt-repository ppa:fkrull/deadsnakes
sudo apt-get update
sudo apt-get install python3.5
```
To set up openjudge
```bash
cd ~
mkdir temporary_directory
cd temporary_directory

virtualenv -p python3.5 environment
source environment/bin/activate
pip install openjudge
```

Now simply create the folder `ContestData` in `~/temporary_directory`. To run openjudge you will have to activate the environment with `source environment/bin/activate` and then run `openjudge`

**Comment by Dedock** [comment]
Thanks!!! It works) It has a bit simple interface than the previous version, but it works! how can other people get accesses to my computer or what is the best way to deploy it on a remote server?

**Comment by theSage21** [comment]
Since this is meant for small competitions of 20-30 people I'd recommend that you don't put it on remote servers. There are too many security issues that I have not considered.

If you are connected to a wifi network / LAN, you can let people on the same network access this site by providing them with your IP address.

If your IP is `192.168.4.5` you can run `openjudge 0.0.0.0 8095` instead of `openjudge` to let people access the site by typing `192.168.4.5:8095` in their browsers.

**Comment by Dedock** [comment]
okay) maybe I don't understand something, can you give me a sample solution for problems in contest data folder(i tried judge 'code' wich i saw in the screenshot, but it doesn't work)

**Comment by theSage21** [comment]
for the first problem:
```python
for i in range(5):
    print(input())
```

for the second one:

```python
for i in range(5):
    x = int(input())
    print(x**2)
```

**Comment by Dedock** [comment]
thanks again! but i can't access to site from another computer((

**Comment by Dedock** [comment]
Hello, I still can't get access from a remote computer( is it working on your computer? can it be connected with settings on my computer?

**Comment by theSage21** [comment]
I've asked a few friends to test it out. They can access it on their machines. It seems to be an issue with your connection settings.
