### ISSUE TITLE
Not able to interpret this

### ISSUE THREAD

**Issue by proRamLOGO** [theSage21/openJudge#18]
I am not able to interpret the following lines
`command = wrap.format(code=codepath, input=inpath)

        commands.append(command)

    tools.log('Adding attempt {} to job queue'.format(attempt_id))

    job_queue.put({'evaluated': False, 'attempt_id': attempt_id,
                   'inp_paths': inp_paths,
                   'code_path': codepath, 'commands': commands,
                   'out_list': out_list, 'user': user,
                   'qpk': qpk})
`
Also please tell what is "log" ??

**Comment by theSage21** [comment]
`log` is a function  defined in tools. It is an equivalent of print.
`wrap` is a wrapper string as defined in contest `wrappers.json`. This is the format that the code command is supposed to follow. Different languages are supported by calling different wrappers with the same arguments, namely `codepath and inpath`
