### ISSUE TITLE
newlines in text

### ISSUE THREAD

**Issue by jhudsy** [theSage21/openJudge#23]
I can't seem to be able to get a newline to appear in when the statement is displayed by openJudge. Am I missing something obvious?

**Comment by theSage21** [comment]
Do you mean the question statement?

**Comment by theSage21** [comment]
In any case, I've released the Markdown formatting I've been working on. new lines work in that wherever you need them to. [v2.0.14](https://github.com/theSage21/openJudge/releases/tag/v2.0.14)

**Comment by jhudsy** [comment]
The markdown formatting is brilliant, and yes, it was in the question statements. Many thanks for this.

**Comment by theSage21** [comment]
@jhudsy if openJudge has been useful a star would be nice 😄
