### ISSUE TITLE
webserver

### ISSUE THREAD

**Issue by jhudsy** [theSage21/openJudge#29]
The default webserver seems to occasionally hang, I've found that using paste as a server seems much more stable, so might be a useful enhancement (achievable by adding a server="paste" to the app.run line in cli.py and another entry in install_requires in setup.py).

All the best.

**Comment by theSage21** [comment]
I was initially using paste but encountered https://github.com/theSage21/openJudge/issues/20 Investigating why might help this case. Other than the analytics page, paste was glorious.

**Comment by jhudsy** [comment]
Ah, I haven't been able to get analytics to work (even with everything installed, it tells me that pandas or matplotlib is missing, so I haven't been able to replicate this error on my end.
