### ISSUE TITLE
Decoding file content for comparing them

### ISSUE THREAD

**Issue by cquark7** [theSage21/openJudge#32]
In this project, you're comparing file content after decoding them.
```Python 
result = result and stdout.decode().strip() == self.out.strip()
```
Any specific reason for using this approach?

**Comment by theSage21** [comment]
From what I remember, this project actually ran your code instead of just comparing outputs. Because of that, I had to capture stdout from a subprocess pipe. Stdout was provided as binary for some reason and so I had to decode it.

**Comment by theSage21** [comment]
The first result was whether the subprocess ran without errors (this caught compiler errors etc from languages like C) and the next part only got decoded if no errors were raised.

**Comment by cquark7** [comment]
Thanks for explaining.
