### ISSUE TITLE
Code check is slow

### ISSUE THREAD

**Issue by shudwi** [theSage21/openJudge#5]
Compiling and checking by hand is faster than the openjudge slave.  
Lack of logging is not allowing me to identify which part of the judge is slow.  
Possibly file access is slow on my machine.

**Comment by theSage21** [comment]
On my setup the calibration question is very quick.  
If you are not on your own network it might be that the network is having huge latency.

The logging aspect is still under development. I have added debug steps though in the latest push.

**Comment by theSage21** [comment]
This is fixed in v0.3.x
